dotnet/deployment-tools

src/installer/publish/Directory.Build.targets

Fixes https://github.com/dotnet/deployment-tools/issues/13

Enable publishing of all nupkg artifacts

---

src/clickonce/Directory.Build.targets
src/installer/Directory.Build.targets
src/installer/publish/publish-final.proj

Updating final artifacts path for this repo.

Update final artifacts path

---

eng/Signing.props
eng/jobs/windows-build.yml

Sign binaries early to include in VS packages.

Binary signing

---

src/clickonce/MageCLI/Application.resx
src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.es.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.it.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf

Remove comment from resx file

---

src/clickonce/launcher/HostFinder.cs

Enables activation of arm64 .NET (Core) FDD applications.

Allow Launcher to find host for unknown architectures

---

src/clickonce/MageCLI/MageCLI.csproj

Creates a global tool for Mage.NET.

Enable packaging of Mage.NET

---

src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.es.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.it.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf

Loc checkin

---

eng/SignCheckExclusionsFile.txt
eng/Signing.props

Skip signing of non-Microsoft binaries

Skip signing of non-Microsoft binaries

---

src/clickonce/MageCLI/MageCLI.csproj

Changing Mage package name to Microsoft.DotNet.Mage.

Package name update

---

Documentation/dotnet-mage/README.md

Port https://github.com/dotnet/deployment-tools/pull/64 to release/5.0
Update README.md
Update links and versions for .NET 5 release.

[release/5.0] Update README.md

---

eng/Versions.props

Update versioning to 6.0

---

src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf

@NikolaMilosavljevic  Updating/fixing few previous translations.

[Loc] Loc update

---

azure-pipelines.yml

Addresses https://github.com/dotnet/deployment-tools/issues/81

Adding Windows Arm64 to build pipeline

---

eng/Versions.props

Updating branding for Preview 1.

Preview.1 branding

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

The .NET releases nupkg does not contain a proper description.

Add package description

---

README.md

Build status and links to builds will show on the repo landing page (Readme.md)

Add build status to Readme.md

---

azure-pipelines.yml

Step 2 in the guide: https://github.com/dotnet/arcade/blob/master/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md
Master branch will be removed later.

Add main branch to yml files

---

src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.cs.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.de.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.es.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.fr.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.it.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.ja.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.ko.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.pl.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.pt-BR.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.ru.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.tr.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.zh-Hans.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.zh-Hant.xlf
src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.es.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.it.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf

Latest translations.
@crsuzukimsft

Loc update

---

src/Microsoft.Deployment.DotNet.Releases/src/ProductCollection.cs

Set default URL to point to CDN

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

Stabilizing version for 1.0 release.

Stabilize version to 1.0

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

We just published preview2 on NuGet

Update to preview3

---

eng/Versions.props

Versioning update for 6.0.1 preview.

Preview 6.0.1 versioning

---

global.json
src/clickonce/MageCLI/Certificate.cs
src/clickonce/MageCLI/Command.cs
src/clickonce/MageCLI/Mage.cs
src/clickonce/MageCLI/MageCLI.csproj
src/clickonce/MageCLI/Misc.cs

Backport of the following 2 changes:
https://github.com/dotnet/deployment-tools/commit/7c04a33406de3587f89d911c692e6e1a1221d047
https://github.com/dotnet/deployment-tools/commit/9c32437e883b1a4611e6ad17ddecfabfc282bda7

Backport of fixes for 6.0.1

---

NuGet.config
eng/Version.Details.xml

Related to https://github.com/dotnet/source-build/issues/2625
I will also be making the appropriate darc subscription updates once merged.

Update source-build dependency to source-build-externals

---

azure-pipelines.yml

Remove obsolete parameter `dependsOn` that was removed from `/eng/common/templates/post-build/post-build.yml`

Remove obsolete parameter

---

eng/jobs/windows-build.yml

Related to https://github.com/dotnet/arcade/issues/8477

Enable SBOM generation

---

eng/Versions.props

Update versioning to 7.0.0 preview 1

Update versioning to 7.0.0 preview 1

---

azure-pipelines.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/run-publish-project.yml

Updating few remaining instances of VS2017 agents to VS2019.

Move to VS2019 build agents

---

src/clickonce/native/build.cmd

Enables building on machines with VS 2022 installed.

Add build support for VS 2022

---

eng/Versions.props

Update versioning for upcoming Preview 2 release

Update versioning for upcoming Preview 2 release

---

eng/jobs/bash-build.yml
eng/jobs/windows-build.yml

Update public build pool from NetCore1ESPool-Public to NetCore-Public

Update public build pool

---

azure-pipelines.yml
eng/common/templates/job/execute-sdl.yml
eng/common/templates/job/onelocbuild.yml
eng/common/templates/job/source-index-stage1.yml
eng/common/templates/jobs/jobs.yml
eng/common/templates/post-build/post-build.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/windows-build.yml

We need to use newer images. Old ones were deprecated.

Update build images

---

src/clickonce/MageCLI/MageCLI.csproj

Fixes CG issue: https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-deployment-tools/alert/7358563?typeId=6245928&pipelinesTrackingFilter=0
This is pulled in indirectly via Microsoft.Build.Tasks.Core. The fix is adding a direct package reference.

Update System.Security.Cryptography.Xml dependency to 4.7.1

---

eng/Configurations.props
eng/Versions.props
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/clickonce/MageCLI/MageCLI.csproj

Also includes port of some versioning-related changes from release/7.0.

Versioning for 8.0 preview 1

---

.config/tsaoptions.json

Add tsaoptions file

---

src/clickonce/launcher/Launcher.csproj

This is a cherry-pick of [c1b098fd20048836d6432eb61901ac2f0cc1e312 ](https://github.com/dotnet/deployment-tools/pull/250/commits/50d0ba151c722044a2fb5b20f889cd618909442a) - port from `release/8.0-preview1 branch`

Launcher PDB should be published

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml

Fixes: https://github.com/dotnet/deployment-tools/issues/264

Enable source-build pre-built detection

---

NuGet.config

Fixes: https://github.com/dotnet/deployment-tools/issues/263

Remove old dotnet feeds

---

eng/Versions.props
tools-local/tasks/installer.tasks/installer.tasks.csproj

Rev nuget package dependencies

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

Updating branding in main to 2.0.0 preview 1 now that we've shipped 1.0.0

Update branding for Releases.json library

---

eng/Configurations.props
eng/Versions.props
global.json
src/Microsoft.Deployment.DotNet.Releases/tests/Microsoft.Deployment.DotNet.Releases.Tests.csproj
src/clickonce/MageCLI/MageCLI.csproj

8.0 GA versioning

---

eng/Versions.props

Update Versions.props for Preview 2 release

---

eng/jobs/windows-build-PR.yml
eng/jobs/windows-build.yml

Unblocks broken official builds

Update MicroBuild plugin to v4

---

src/Microsoft.Deployment.DotNet.Releases/src/ProductCollection.cs

Update the URL for the CDN. Related to https://github.com/dotnet/core/issues/9671. This is a port of the change from main
Low
Manually verified

[release/8.0] Update URL for releases-index.json

---

src/Microsoft.Deployment.DotNet.Releases/src/ProductCollection.cs

Update the URL for the CDN. Related to https://github.com/dotnet/core/issues/9671. This is a port of the change from main
Low
Manually verified

[release/9.0] Update URL for releases-index.json

---

azure-pipelines.yml

This is a required by compliance.
[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2668499&view=results) (internal Microsoft link)

Enable SDL in official build

---

.github/CODEOWNERS

Introducing the CODEOWNERS file in this repo.

Introduce the CODEOWNERS file
