dotnet/deployment-tools

eng/SignCheckExclusionsFile.txt
src/clickonce/launcher/Constants.cs
src/clickonce/launcher/HostFinder.cs
src/clickonce/launcher/Launcher.csproj
src/clickonce/launcher/LauncherException.cs
src/clickonce/launcher/Logger.cs
src/clickonce/launcher/ProcessHelper.cs
src/clickonce/launcher/Program.cs
src/clickonce/launcher/ResourceReader.cs
src/clickonce/shared/NativeMethods.cs

Add ClickOnce Launcher
Launcher will be used to activate .NET (Core) apps, directly (if they are EXEs) or using a host discovered on user's machine. Initially, only default global shared host location is checked - others will be added at later time.
Logging is optional, and can be configured by user with a registry key/value that will be documented in existing ClickOnce documentation.

Add ClickOnce Launcher

---

src/clickonce/Directory.Build.props
src/clickonce/launcher/Launcher.csproj
src/clickonce/pkg/Directory.Build.props
src/clickonce/pkg/projects/Directory.Build.props

Simple change to enable building launcher package - a single one as Launcher is an MSIL binary.
Majority of changes are about shared packaging infra being moved 1 or 2 levels up the tree.

Enable packaging of Launcher nuget package for VS

---

eng/Signing.props

FileSignInfo@Include value is case-sensitive - update the value for Launcher binary signing exclusion.
Launcher is a template binary, that should not be signed.

Launcher should not be signed

---

src/clickonce/MageCLI/Mage.cs

This change modifies the default update behavior in Mage generated manifests to match default Visual Studio experience.
In Visual Studio, when developer enables ClickOnce updates, default option is for updates to happen before the application starts. This enables end-user to install the update as soon as it's available.
Mage default was to check for update after app was launched, and offer it on next app launch.
I believe these two experiences should match and provide end-user with update sooner.
Developers can still modify their deployment manifest to get the old behavior, if desired.

Check for updates before starting the app

---

src/clickonce/MageCLI/MageCLI.csproj

As previously planned, final name of Mage CLI tool will be "dotnet-mage".
Deployed as a .NET Global tool would allow usage as "dotnet-mage" and "dotnet mage" which fits the existing naming model for Microsoft's .NET Global tools.

Rename Mage.NET to dotnet-mage

---

src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck.pkgproj

Fixing https://github.com/dotnet/deployment-tools/issues/18
VS.Redist.Common.NetCoreCheck -> VS.Redist.Common.NETCoreCheck

Updating name of NETCoreCheck nuget package to follow naming convention

---

Documentation/dotnet-mage/README.md

Updating documentation to reflect changes in the tool name:
- `dotnet mage` or `dotnet-mage` instead of `mage.net` and `Mage.NET`
Fixes: https://github.com/dotnet/deployment-tools/issues/49

Update dotnet-mage documentation - new tool name

---

eng/Versions.props
src/clickonce/launcher/Launcher.csproj
src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck.pkgproj

Updating package versioning - removing pre-release labels.
Had to update IsShipping and IsShippingPackage to 'true' to get versioning tasks to work on VS packaging. While the packages are now binplaced under 'Shipping' folder, they will still get automatically published to VS Feed.

Updating package versioning for RTM build

---

src/clickonce/launcher/Launcher.csproj
src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck.pkgproj

VS.* packages should not use stable versions - reverting partial change in PR: https://github.com/dotnet/deployment-tools/pull/59

Marking non-shipping packages accordingly

---

src/clickonce/pkg/projects/NetCoreCheck/Directory.Build.props
src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck-NonShipping.pkgproj
src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck-Shipping.pkgproj

Introducing another NETCoreCheck package, for nuget.org release.
- Stable versioning
- New name: Microsoft.NET.Tools.NETCoreCheck

New NETCoreCheck package for nuget.org release

---

src/clickonce/pkg/projects/NetCoreCheck/Directory.Build.props
src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck-NonShipping.pkgproj
src/clickonce/pkg/projects/NetCoreCheck/NetCoreCheck-Shipping.pkgproj

Port of https://github.com/dotnet/deployment-tools/pull/63
Introducing another NETCoreCheck package, for nuget.org release.
- Stable versioning (when building in release branches)
- New name: Microsoft.NET.Tools.NETCoreCheck

New NETCoreCheck package for nuget.org release - port of PR #63

---

eng/Subsets.props
eng/Version.Details.xml
eng/Versions.props
eng/common/SetupNugetSources.ps1
eng/common/SetupNugetSources.sh
eng/jobs/steps/upload-job-artifacts.yml
global.json

This PR includes several changes:
- Updates Arcade tooling with fixes for NuGet signing validation
- Temporarily disables build and packaging of native projects - see issue https://github.com/dotnet/deployment-tools/issues/77
- Fixes YAMLs to skip publishing steps for builds that do not produce any packages or other artifacts

Update Arcade tooling

---

eng/Subsets.props
global.json
src/clickonce/MageCLI/Application.cs
src/clickonce/MageCLI/Application.resx
src/clickonce/MageCLI/Certificate.cs
src/clickonce/MageCLI/Command.cs
src/clickonce/MageCLI/CryptoApi.cs
src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.es.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.it.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf
src/clickonce/native/Windows/gen-buildsys-win.bat
src/clickonce/native/build.cmd
src/clickonce/native/build.proj

Besides updating toolset to 5.0.2, this PR includes the following changes:
- re-enable native projects
- enable linking to SDK libraries in both local or global locations
- fix all issues in managed code caused by new strict rules in 5.0.2 - condition APIs and constructs that are obsolete in .NET 5 and add guards for platform-specific APIs
- add condition and error message for signing in dotnet-mage - prevents errors on unsupported platforms

Update toolset to 5.0.2

---

eng/Version.Details.xml
eng/Versions.props
global.json

Update Arcade toolset with latest - this fixes the issue with symbol publishing due to some missing nuget feeds.

Arcade update January 2021

---

src/Microsoft.Deployment.DotNet.Releases/src/AspNetCoreReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/Cve.cs
src/Microsoft.Deployment.DotNet.Releases/src/JsonExtensions.cs
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/Microsoft.Deployment.DotNet.Releases/src/Product.cs
src/Microsoft.Deployment.DotNet.Releases/src/ProductCollection.cs
src/Microsoft.Deployment.DotNet.Releases/src/ProductRelease.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseFile.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseVersion.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseVersionConverter.cs
src/Microsoft.Deployment.DotNet.Releases/src/RuntimeReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/SupportPhaseConverter.cs
src/Microsoft.Deployment.DotNet.Releases/src/Utils.cs
src/Microsoft.Deployment.DotNet.Releases/src/WindowsDesktopReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/tests/Microsoft.Deployment.DotNet.Releases.Tests.csproj
src/Microsoft.Deployment.DotNet.Releases/tests/ProductCollectionTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ProductTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ReleaseVersionTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/data/6.0/releases.json
src/Microsoft.Deployment.DotNet.Releases/tests/data/releases-index.json
src/Microsoft.Deployment.DotNet.Releases/tests/data/releases.json

Added `DebuggerDisplay` attributes to `Product` and `ProductRelease` classes:
- Minor clean up for readability
- Use C# 8
- Using declarations
- Pattern matching
- Tuples
- Use `string.IsNullOrWhiteSpace` instead of `string.IsNullOrEmpty`
- Remove redundant parenthesis
- More consistent usage of `var`, following _.editorconfig_
- Prefer object/collection initializers
- Use discards where appropriate
- Prefer expression bodied members where possible
- Ternary expressions, each branch on it's own line when spanning multiple lines
- Added release 6.0 to test cases
- Update unit tests accordingly
/cc @joeloff

Add debugger display bits

---

eng/Subsets.props

Temporarily disable building native projects, to unblock e2e CI build.

Temporarily disable building native projects

---

src/clickonce/MageCLI/Command.cs

Fixes: https://github.com/dotnet/deployment-tools/issues/101
When specifying minimum version, app stops checking for updates. This is different from VS experience, where you can specify that app checks for updates and requires a specific minimum version.
This is a simple change, that follows Mage tool's documentation which already specifies that `-mv` option would make the app installable. The fix enforces that, and reestablishes default Mage experience - apps being installed should check for updates.
The change includes removal of the block that prevented user from specifying both `-install` and `-mv` options. This allows user to override new decision, to make install true if `-mv` is specified, for compatibility. Note that Mage documentation implies that `-install` and `-mv` options are …

Enable updates with minimum version

---

src/Microsoft.Deployment.DotNet.Releases/src/Product.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ProductReleaseTests.cs

Address #116 
Processing releases currently requires starting with an index file, either local or remote. We have need to process standalone releases.json files to support various tools, especially where a new release is being published, before being merged into the existing releases.json.

Add method to parse single release.json files

---

eng/Subsets.props
eng/Version.Details.xml
eng/Versions.props
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/Microsoft.Deployment.DotNet.Releases/tests/Microsoft.Deployment.DotNet.Releases.Tests.csproj
tools-local/tasks/installer.tasks/installer.tasks.csproj
tools-local/tasks/tasks.proj

Related to https://github.com/dotnet/source-build/issues/2458 and https://github.com/dotnet/source-build/issues/2430.
There are two prebuillts remaining related to net 4.5.2 reference packages which will be addressed in https://github.com/dotnet/source-build-reference-packages

Eliminate source-build prebuilts

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

Revert stable version to preview2 for now until we figure out the separate release process within the repo.
Should address #142

Revert version to preview2 to unblock CI

---

tools-local/scripts/arm32_ci_script.sh
tools-local/scripts/dev/master-build-deb-rpm-docker.sh
tools-local/scripts/dev/release-2.1-build-deb-rpm-docker.sh

Updating Docker image tag references that are obsolete and replaced by references to mcr.microsoft.com/dotnet-buildtools/prereqs. See dotnet/dotnet-docker#2848.

Update tag references to dotnet-buildtools/prereqs

---

src/Microsoft.Deployment.DotNet.Releases/src/ProductRelease.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ProductReleaseTests.cs

The ProductRelease.File property did not include SDK files. The SDK files also included marketing files incorrectly.

Include SDK files in the File property, exclude marketing files

---

src/Microsoft.Deployment.DotNet.Releases/src/ReleaseVersion.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ReleaseVersionTests.cs

Comparisons for numeric identifiers was missing good test cases which didn't catch this issue previously. It failed for single digit values and performed an incorrect comparison when the numeric identifiers were off different lengths.

Fix comparison for numeric identifiers

---

azure-pipelines.yml
eng/jobs/bash-build.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/windows-build.yml

We are moving to 1ES hosted pools. This PR update pipeline yaml to use new pools.
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
/cc: @jonfortescue

Migrate to 1ES hosted pools

---

azure-pipelines.yml
eng/jobs/bash-build.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/windows-build.yml

Same as https://github.com/dotnet/deployment-tools/pull/166 but for `release/6.0` branch.
/cc: @jonfortescue

[release/6.0] Migrate to 1ES hosted pools

---

src/clickonce/MageCLI/Certificate.cs
src/clickonce/MageCLI/Command.cs
src/clickonce/MageCLI/Mage.cs
src/clickonce/MageCLI/MageCLI.csproj
src/clickonce/MageCLI/Misc.cs

Fixes: https://github.com/dotnet/deployment-tools/issues/170
Updating dotnet-mage tool to target .NET 6.
Includes changes in code to work-around updates in API support and platform applicability.
Tested on docker image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019

Dotnet-mage should target net6.0

---

azure-pipelines.yml
eng/jobs/bash-build.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/windows-build.yml

Same as https://github.com/dotnet/deployment-tools/pull/166 but for `release/5.0` branch.
/cc: @jonfortescue

[release/5.0] Migrate to 1ES hosted pools

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseVersion.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleasesResources.Designer.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleasesResources.resx
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.cs.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.de.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.es.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.fr.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.it.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.ja.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.ko.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.pl.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.pt-BR.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.ru.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.tr.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.zh-Hans.xlf
src/Microsoft.Deployment.DotNet.Releases/src/xlf/ReleasesResources.zh-Hant.xlf
src/Microsoft.Deployment.DotNet.Releases/tests/ReleaseVersionTests.cs

- Don't use regex for parsing.
- Making regex pattern public - there are use cases where we want to extract a version embedded inside other strings
- Add `Parse` and `TryParse` methods to be more consistent with `Version` class
- Cleaning up exception handling
- More unit tests

Clean up parsing logic for ReleaseVersion

---

azure-pipelines.yml
eng/Signing.props
src/installer/publish/prepare-artifacts.proj

Switching back to sign binaries during build and publishing, instead of during post-build.

Fix for package signing

---

src/clickonce/launcher/HostFinder.cs
src/clickonce/shared/NativeMethods.cs

Fixes: https://github.com/dotnet/deployment-tools/issues/138
Launcher will find proper x64 host location on arm64 machines.
Since .NET 6, x64 .NET, on arm64 systems, is installed to `\Program Files\dotnet\x64`.

Find correct x64 host on arm64 machines

---

Documentation/dotnet-mage/ApplicationDeployment.cs
src/clickonce/MageCLI/Application.cs
src/clickonce/MageCLI/Application.resx
src/clickonce/MageCLI/Command.cs
src/clickonce/MageCLI/Mage.cs
src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.es.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.it.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf
src/clickonce/launcher/Program.cs

Fixes: https://github.com/dotnet/deployment-tools/issues/53
Launcher is being extended to share ClickOnce ApplicationDeployment properties with the application being launched (.NET based). Properties are shared via Environment variables.
Variable names closely match old ClickOnce ApplicationDeployment class: https://docs.microsoft.com/en-us/dotnet/api/system.deployment.application.applicationdeployment?view=netframework-4.8
New environment variables use the same name as old ones, with addition of `ClickOnce_` prefix:
```
ClickOnce_IsNetworkDeployed
ClickOnce_ActivationUri
ClickOnce_CurrentVersion
ClickOnce_DataDirectory
ClickOnce_IsFirstRun
ClickOnce_TimeOfLastUpdateCheck
ClickOnce_UpdatedApplicationFullName
ClickOnce_UpdatedVersion
ClickOnce_UpdateLocation
```
New property is being …

Allow apps to access ClickOnce deployment properties

---

eng/Versions.props
src/Microsoft.Deployment.DotNet.Releases/src/AspNetCoreReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/Cve.cs
src/Microsoft.Deployment.DotNet.Releases/src/JsonExtensions.cs
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/Microsoft.Deployment.DotNet.Releases/src/Product.cs
src/Microsoft.Deployment.DotNet.Releases/src/ProductCollection.cs
src/Microsoft.Deployment.DotNet.Releases/src/ProductRelease.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseFile.cs
src/Microsoft.Deployment.DotNet.Releases/src/ReleaseVersionConverter.cs
src/Microsoft.Deployment.DotNet.Releases/src/RuntimeReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/SdkReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/src/SerializerOptions.cs
src/Microsoft.Deployment.DotNet.Releases/src/SupportPhase.cs
src/Microsoft.Deployment.DotNet.Releases/src/SupportPhaseConverter.cs
src/Microsoft.Deployment.DotNet.Releases/src/Utils.cs
src/Microsoft.Deployment.DotNet.Releases/src/VersionConverter.cs
src/Microsoft.Deployment.DotNet.Releases/src/WindowsDesktopReleaseComponent.cs
src/Microsoft.Deployment.DotNet.Releases/tests/CveTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/Microsoft.Deployment.DotNet.Releases.Tests.csproj
src/Microsoft.Deployment.DotNet.Releases/tests/ProductCollectionTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ProductReleaseTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ProductTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ReleaseFileTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/SupportPhaseConverterTests.cs
src/Microsoft.Deployment.DotNet.Releases/tests/TestBase.cs
src/Microsoft.Deployment.DotNet.Releases/tests/UtilsTests.cs

This PR removes the Newtonsoft.Json dependency. Additionally, the library now only support .NET Standard 2.0

Convert to System.Text.Json

---

eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml

Arcade infra is stuck in https://github.com/dotnet/deployment-tools/pull/219 - we don't want to merge that PR until we fork for 7.0.
Updating pools in Arcade infra.

Update pool in Arcade infra

---

eng/Versions.props
src/clickonce/MageCLI/MageCLI.csproj
tools-local/tasks/installer.tasks/installer.tasks.csproj

Fixes:
- Update NuGet.Protocol and related packages to 4.9.6
- Add explicit dependency to System.Drawing.Common 4.7.2 package, in MageCLI project

Update package references to resolve warnings

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/Microsoft.Deployment.DotNet.Releases/src/Product.cs
src/Microsoft.Deployment.DotNet.Releases/src/ProductCollection.cs
src/Microsoft.Deployment.DotNet.Releases/src/Utils.cs

When the CDN is updated, default cache headers can still result in retrieving stale copies of the releases JSON files. Instead, we configure the default headers to turn caching off.

Turn of caching

---

src/Microsoft.Deployment.DotNet.Releases/src/Product.cs
src/Microsoft.Deployment.DotNet.Releases/tests/ProductTests.cs

We need a private setter to allow STJ to set read-only properties.
Also updating the unit tests to check for this.

Add private setter

---

azure-pipelines.yml
eng/jobs/windows-build.yml

We only run it in Windows x64 jobs to limit resource usage.

Enable CodeQL

---

Directory.Build.targets

We were setting NETCoreAppMaximumVersion property to a repo-specific value, constructed from `MajorVersion` and `MinorVersion`. This causes issues for projects that use custom versioning.
There is no need for this, as the property is set by .NET SDK.

Do not set repo-specific NETCoreAppMaximumVersion property

---

src/clickonce/launcher/Program.cs

Fixes: https://github.com/dotnet/deployment-tools/issues/236 and https://github.com/dotnet/deployment-tools/issues/113
This work enables .NET app, deployed using ClickOnce, to use the activation arguments.
This solves two scenarios:
1) app was activated using appref-ms shortcut and custom arguments were provided on the command-line
2) app was activated using a file with custom extension, registered using file association feature
Launcher reads the `AppDomain.CurrentDomain.SetupInformation.ActivationArguments.ActivationData` array and sets some environment variables if array is non-empty.
`ClickOnce_ActivationData_Count`
If this variable exists, the value is the count of elements in ActivationData string array.
`ClickOnce_ActivationData_<n>`
For each element in array, new environment …

Expose ActivationData to launched .NET app

---

eng/Versions.props
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

Adding `net7.0` to enable source build support and moving to a non-prerelease STJ dependency.
Bumping the preview label as well since we published preview5 last year.

Add net7.0 to support source build

---

src/clickonce/launcher/Launcher.csproj

Enables publishing of Launcher PDB to symbol server.
I've verified that Launcher symbols are now included in PdbArtifacts: https://dev.azure.com/dnceng/internal/_build/results?buildId=2112719&view=logs&j=6c8d8e10-00f6-599f-9a42-dac02746d52f&t=9f58a776-c5c2-5290-ec37-0f37735a229a

Launcher PDB should be published

---

azure-pipelines.yml

Official builds were not pushing the output intermediate package.
Fixes #257

Update source build leg to use default parameters

---

eng/Versions.props
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

The Microsoft.Deployment.DotNet.Releases package had the pre-release label "preview6.1". The ".1" is the pre-release iteration. The 6 should have been the pre-release iteration. Fix this up by setting the pre-release iteration.

Fixup versioning for packages

---

Build.proj
eng/SourceBuild.props
tools-local/tasks/tasks.proj

﻿### Summary of the changes
This is part of the source-build work to enable trimming of net4* targets. Parent repos (`installer` and `sdk`) have been updated, so the next step is to update dependencies, like `deployment-tools`.
Here's how this is consumed: https://github.com/dotnet/arcade/pull/12785
Top-level tracking issue: https://github.com/dotnet/source-build/issues/3014
This essentially just avoids building net4* TFMs when building Linux source build.
Fixes: https://github.com/dotnet/deployment-tools/issues/217

Trim away netframework targets in source-build

---

src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj

Fixes #288
According to https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1195, trimming in only supported on netcoreapp3.0 and above.  Microsoft.Deployment.DotNet.Releases targets netstandard2.0

Remove trimmable setting which is not supported in netstandard2.0

---

src/clickonce/native/build.cmd

Hi,
I was trying to build this project on my own machine which has only VS2022 installed and I found out I was not able to build it because the vars were simply setup wrong. Fixing those made the project building successfully.
Feel free to ping me if you have any question but the PR is pretty much self-explanatory.
Cheers!

build.cmd: Fix VS2022 setup vars

---

global.json

Updating versions of `Microsoft.Build.NoTarget` and `Microsoft.Build.Traversal` SDKs to the latest available.

Update SDK versions

---

eng/Subsets.props
src/clickonce/MageCLI/MageCLI.csproj
src/clickonce/launcher/Launcher.csproj

The native code for this repo doesn't build on non-Windows. Build the minimal subset required for downstream SDK consumption.

Fix casing and Subsets

---

eng/jobs/bash-build.yml
eng/jobs/osx-build.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/run-publish-project.yml
eng/jobs/windows-build.yml

Noticed this while looking at a build log. `NuGetAuthenticate@0` is deprecated.

Update NuGetAuthenticate@0 in pipelines

---

azure-pipelines-PR.yml
azure-pipelines.yml
eng/jobs/windows-build-PR.yml

Splits the existing CI pipeline into two separate pipelines:
- azure-pipelines-PR.yml: for public builds - This is the same as the original content except that conditional logic has been removed that was meant to support internal builds.
- azure-pipelines.yml: for internal builds - Uses the 1ES pipeline template pattern
Successful validation builds:
- internal: https://dev.azure.com/dnceng/internal/_build/results?buildId=2414346&view=results
- public: https://dev.azure.com/dnceng-public/public/_build/results?buildId=617819&view=results

1ES pipeline templates

---

azure-pipelines-PR.yml
azure-pipelines.yml
eng/jobs/prepare-signed-artifacts.yml
eng/jobs/steps/upload-job-artifacts-PR.yml
eng/jobs/steps/upload-job-artifacts.yml
eng/jobs/windows-build-PR.yml
eng/jobs/windows-build.yml

Splits the existing CI pipeline into two separate pipelines:
- azure-pipelines-PR.yml: for public builds - This is the same as the original content except that conditional logic has been removed that was meant to support internal builds.
- azure-pipelines.yml: for internal builds - Uses the 1ES pipeline template pattern. I've ported the implementation from `main` which simplified existing ymls quite a bit.
Successful validation builds:
- internal: https://dev.azure.com/dnceng/internal/_build/results?buildId=2415618&view=results
- public: https://dev.azure.com/dnceng-public/public/_build/results?buildId=619754&view=results

[release/8.0] 1ES pipeline templates

---

azure-pipelines-PR.yml

This fixes the YML reference for public pipeline.

Fix yml reference

---

azure-pipelines.yml

Removing `-pt` from image names as those are obsolete now. This was blocking the official builds.

Update image names

---

eng/jobs/windows-build-PR.yml
eng/jobs/windows-build.yml

The new version of the powershell script will not place the creds in the nuget.config file, instead it will use standard environment variables. Update the YAML file to use NuGetAuthenticate to avoid a build break that may happen if the credential provider is not available.

Call NuGetAuthenticate after SetupNuGetSources

---

eng/Versions.props

This is necessary so that dotnet/sdk can also downgrade STJ back to 8.0.0. I had to pick 8.0.0 as 8.0.3 isn't available on SBRP.
We can't update to 8.0.4 yet as we don't yet have a VS with S.T.J/8.0.0.4 binding redirects for msbuild on .NET Framework.
This is needed for 9.0 P7. Apparently this doesn't need to be backported as this repo doesn't branch per preview.
cc @rainersigwald @marcpopMSFT @Forgind

Downgrade S.T.J to 8.0.0

---

eng/Versions.props

https://github.com/dotnet/deployment-tools/pull/373 has updated the version of `Microsoft.Build.Tasks.Core` package to 17.8.3.
This causes issues with `dotnet mage` signing step. Example output:
```
dotnet mage -sign files\app.manifest -cf test.pfx -pwd <password>
Internal error, please try again. Could not create hash algorithm object. If the application has been trimmed, ensure the required algorithm implementations are preserved.
at Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFileInternal(X509Certificate2 cert, Uri timestampUrl, String path, Boolean targetFrameworkSupportsSha256, ResourceManager resources, Boolean disallowMansignTimestampFallback)
at Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(X509Certificate2 cert, Uri …
```

Update Microsoft.Build.Tasks.Core package version to 17.9.5

---

Directory.Build.props
Directory.Packages.props
NuGet.config
eng/Version.Details.xml
eng/Versions.props
src/Microsoft.Deployment.DotNet.Releases/src/Microsoft.Deployment.DotNet.Releases.csproj
src/clickonce/MageCLI/MageCLI.csproj

Contributes to https://github.com/dotnet/arcade/issues/15019
- Remove unnecessary package source feeds.
- Move version properties into D.Packages.props as those aren't auto-updated.
- Enable NuGetAudit and make vulnerabilities fail the official build. Otherwise those are warnings.

Enable Central Package Management and NuGetAudit

---

Build.proj
eng/Signing.props

Fixes: https://github.com/dotnet/deployment-tools/issues/398
Native projects are failing due to compiler mismatch between object file produced in the build and dependent lib file produced by `runtime`. Per @MSLukeWest these projects can be disabled. If we ever need to build them again, it will be easy to re-enable them. Historically, compiler mismatch only existed during short period around .NET GA timeframe.
Additionally I've updated the Signing.props file to allow empty sign list as there won't be any artifacts for signing in x86/arm64 builds. This follows existing pattern in `runtime` and `aspnetcore`.

Disable native projects

---

README.md

dotnet-mage tool documentation link was pointed to a non-existant folder, fixed the link.

fix dotnet-mage tool documentation link in readme

---

Build.proj
eng/native/configurecompiler.cmake

Enable native project build. This requires removal of `/GL` for release build, to disable whole-program optimization. This is needed so we can link to `libnethost.lib` which might not be produced with exactly the same compiler version.

Enable native projects

---

eng/Versions.props
eng/native/configurecompiler.cmake
global.json
src/clickonce/MageCLI/MageCLI.csproj

Includes:
- Changes to enable stable versioning for 9.0 GA release
- Fix for native build required due to build host machine changes - a backport from main
- Suppression of SYSLIB0057 - deprecated API in 9.0 GA SDK

Stable versioning for 9.0 GA

---

eng/jobs/windows-build-PR.yml
eng/jobs/windows-build.yml

Current version of MicroBuildSigningPlugin is rather old and needs to be updated to the latest version, to avoid build errors - https://dev.azure.com/dnceng/internal/_build/results?buildId=2613908&view=logs&j=067ed0b4-dcd1-5080-5399-b81cd109269d&t=184ceaac-4a3e-56b9-5eef-ea35f642522e
This is already the case in `main` - updating `release/9.0` branch.

Update version of MicroBuildSigningPlugin to @4

---

Build.proj

Comment is not needed anymore as native projects were re-enabled with https://github.com/dotnet/deployment-tools/pull/406
I don't think we need any comments for this property as the name is self-explanatory.

Remove comment about disabling native projects

---

src/clickonce/MageCLI/Application.resx
src/clickonce/MageCLI/xlf/Application.cs.xlf
src/clickonce/MageCLI/xlf/Application.de.xlf
src/clickonce/MageCLI/xlf/Application.es.xlf
src/clickonce/MageCLI/xlf/Application.fr.xlf
src/clickonce/MageCLI/xlf/Application.it.xlf
src/clickonce/MageCLI/xlf/Application.ja.xlf
src/clickonce/MageCLI/xlf/Application.ko.xlf
src/clickonce/MageCLI/xlf/Application.pl.xlf
src/clickonce/MageCLI/xlf/Application.pt-BR.xlf
src/clickonce/MageCLI/xlf/Application.ru.xlf
src/clickonce/MageCLI/xlf/Application.tr.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hans.xlf
src/clickonce/MageCLI/xlf/Application.zh-Hant.xlf

Added a white space to fix alignment of the `-a` option- 
```
Q:\mage>Q:\mage\artifacts\bin\MageCLI\Debug\net8.0\dotnet-mage
Commands
-New <file_type>                -n
-Update <file_name>             -u
-Sign <file_name>               -s
-ClearApplicationCache          -cc
-Verify <manifest_file_name>    -ver
-AddLauncher <binary_to_launch> -al
-Help [verbose]                 -h -?
Options
-Algorithm <sha256RSA>           -a
-AppCodeBase <path>               -appc
-AppManifest <path>               -appm
-CertFile <file_name>             -cf
```

fix alignment in the options help message

---

.github/policies/untriaged.yml
.github/workflows/labeler-cache-retention.yml
.github/workflows/labeler-predict-issues.yml
.github/workflows/labeler-predict-pulls.yml
.github/workflows/labeler-promote.yml
.github/workflows/labeler-train.yml
.github/workflows/labeler.md

These workflows replace the issue-labeler implementation that runs as a GitHub app, allowing training and prediction for the repository's labels without the need for an external service. We will decommission that service once all repositories migrate to the new implementation.
References:
* [Home · dotnet/issue-labeler Wiki](https://github.com/dotnet/issue-labeler/wiki)
* [Onboarding · dotnet/issue-labeler Wiki](https://github.com/dotnet/issue-labeler/wiki/Onboarding)
* [FAQ · dotnet/issue-labeler Wiki](https://github.com/dotnet/issue-labeler/wiki/FAQ)
Once this is merged, we will need to run the 'Labeler: Training' workflow to train new prediction models, then 'Labeler: Promotion' workflow to promote the models into active use, and then I will disable the integration of the legacy …

Onboard the GitHub Action based Issue-Labeler

---

Directory.Packages.props
eng/common/build.sh

MSBuild version in this repo is vulnerable. Updating to next up that is fine.

Update MSBuild versoion to 17.10.29

---

Build.proj
Directory.Build.props
eng/Signing.props
eng/Versions.props
src/DotNetRuntimeValidation/Directory.Build.targets
src/DotNetRuntimeValidation/DotNetRuntimeValidation.csproj
src/DotNetRuntimeValidation/Program.cs
src/DotNetRuntimeValidation/appsettings.json

We hand this tool off to the 1P Gallery team every year - they use it to validate that all runtimes have been installed correctly & are working as expected on their machines. As part of the SFI push, this .exe has to be real-signed, which can no longer be done by hand (we used to hand it off manually via https://github.com/wtgodbe/DotNetRuntimeValidation). I'm proposing checking it in to this repo, rather than making a new one, as this repo is already in the VMR & has already paid the fixed start-up costs for SFI.
I also update branding to 10.0 in this PR

Add DotNetRuntimeValidation tool to deployment-tools
